---
new_page_extension: md
auto_deploy: false
admin_path: backend
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: content/draft_posts
  label: Draft
  create: all
  match: "**/*"
upload_dir: static
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - NODE_VERSION=16.13.0
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
